### ISSUE TITLE
Publishing with CM requires date in the future

### ISSUE THREAD

**Issue by CollierCZ** [Kentico/kontent-delivery-sdk-js#178]
### Brief bug description

When attempting to use `publishOrScheduleLanguageVariant()`, I cannot publish now or at the next scheduled publish

### Repro steps

A few cases
1. Use `publishOrScheduleLanguageVariant` without `.withData` -> type error -- is not a function
2. Use `publishOrScheduleLanguageVariant` with empty `.withData` -> 404 -- "The provided value is not a valid date."
3. Use `publishOrScheduleLanguageVariant` with date in the past in `.withData` -> 400 -> "The provided date value needs to be in the future."

### Expected behavior

For each case, I expect:
1. The ability not to include data 
2. The ability not to specific a time
3. The ability to provide a time in the past and get a 204, as described in the documentation: https://developer.kenticocloud.com/reference#content-management-api-v2-publish-language-variant

### Test environment

Firefox

**Comment by Enngage** [comment]
Moved to https://github.com/Kentico/kontent-management-sdk-js/issues/5
