### ISSUE TITLE
Automatic retry of 429 error in Content Management SDK

### ISSUE THREAD

**Issue by matus12** [Kentico/kontent-delivery-sdk-js#201]
### Motivation

The default retry policy in Content Management SDK could retry the 429 errors and take into consideration the `retry-after` header value. This way I get the maximum possible rate of requests to Kentico Cloud without implementing my own retry policy.

### Proposed solution

Retry 429 errors based on `retry-after` header value.

**Comment by Enngage** [comment]
Moved to https://github.com/Kentico/kontent-management-sdk-js/issues/6
