### ISSUE TITLE
Generate models that comply with tslint recommended rules

### ISSUE THREAD

**Issue by Neytus** [Kentico/kontent-delivery-sdk-js#203]
### Motivation

Creating models with the Model Generator set up for CommonJS module and TypeScript language, does not end up with a result that complies tslint recommended rules.

![image](https://user-images.githubusercontent.com/11269013/59994655-f696ad80-9654-11e9-9b47-767955ec3059.png)

Namely:
* There is a blank line before the first import.
* One line in the commentary above the class exceeds the recommended length of 120 characters.
* There is a missing trailing comma after the _propertyResolver_.

**Comment by Enngage** [comment]
Next version of SDK does not have classes anymore and uses simple type models with interfaces. The model generator will need to be updated so I'll take this there along with the breaking changes.
