### ISSUE TITLE
Debug element is being added while isDeveloperMode is false

### ISSUE THREAD

**Issue by Domitnator** [Kentico/kontent-delivery-sdk-js#255]
### Brief bug description

I noticed that a debug element is being added to the result while isDeveloperMode is set to false

### Repro steps

1. set isDeveloperMode  to false
2. Make a api call
3. console.log the result
4. Notice that a "debug" element is present

![image](https://user-images.githubusercontent.com/13468638/65871259-4edcfa00-e37e-11e9-8a6c-fdf09b69c92f.png)

### Expected behavior

When isDeveloperMode is set to false i would not expect to see a "debug" element

### Test environment

 - Platform/OS: windows
 - Browser chrome
 - Version 7.0.1

### Additional context

I've tested it with the kentico-kontent-nuxt-module but i'm 90% sure it has nothing to do with the module itself

**Comment by Enngage** [comment]
There is very little overhead in displaying the `debug` data, but for clarity I'm taking the `isDeveloperMode` into account so it doesn't show up unless enabled.
