### ISSUE TITLE
Support self signed certificates for proxy's

### ISSUE THREAD

**Issue by Domitnator** [Kentico/kontent-delivery-sdk-js#256]
### Motivation

I am using the proxy feature to talk securely with my secure kentico kontent repository via somee middleware. My middleware is created in .net and running with a self signed certificate. The SDK is throwing a reject error because of the fact that the development endpoint is sucered with a self signed certificate. This makes debugging harder.

### Proposed solution

[Support the axios rejectUnauthorized option](https://github.com/axios/axios/issues/535)

### Additional context

The error that is being thown right now: 
![image](https://user-images.githubusercontent.com/13468638/65880833-b9983080-e392-11e9-9bef-06303ba461a6.png)

**Comment by Domitnator** [comment]
Note: this only happends when call's are made from the (node) server.

**Comment by Enngage** [comment]
Thanks for submitting the issue! 

I've exposed `AxiosRequestConfig` in the `HttpService` so you can now fully configure it as per Axios' documentation. For your scenario you could use it like this: 

```typescript
const client = new DeliveryClient({
    projectId: 'xxx',
    httpService: new HttpService({
        axiosRequestConfig: {
          httpsAgent: new Agent({
              rejectUnauthorized: false
          })
        }
    })
});
```
This commit is not yet released, but will be soon.

**Comment by Domitnator** [comment]
Great! Looks promising! 

Btw: You happen to be at the Kentico Usergroup Meeting in Breda (The Netherlands) on 30 oktober?
