### ISSUE TITLE
Taxonomy for linked items?

### ISSUE THREAD

**Issue by Domitnator** [Kentico/kontent-delivery-sdk-js#271]
### Expected result

We are using typeresolvers and the urlSlugResolver-callback for creating our URL's. But some of the url's are dependant on the taxonomy of the linked item. Is there a way to retrieve the taxonomy of a linked item? We would rather not do a request for every item (which is our solution right now).

### Additional context

The only fields we get right now are:

codename, link, type, urlslug

![image](https://user-images.githubusercontent.com/13468638/69945949-ebd92200-14ea-11ea-90d4-e91245f0a08d.png)

Would be great if we somehow can configure that we also would like to retrieve the taxonomy of the item.

**Comment by Enngage** [comment]
Hi, 

If the link is represented by a linked item and that linked item is present in Delivery API response, you can access full item in the second parameter of the callback - in your image it would be under the `context` property. Can you check that out?

**Comment by rubenberendsen** [comment]
Hi,

We have checked the response of the **context**.item and that is undefined.

![image](https://user-images.githubusercontent.com/38040580/70543635-fccd0780-1b6a-11ea-80fa-54b1e88a6c89.png)

We are doing the following call:

```
/items/disclaimer?depth=999&elements=url,titel,header_afbeelding,introductie_tekst,artikel_tekst,downloads,gerelateerde_pagina_s,selecteer_het_bestand,sitemap
```

We also played with the depth parameter and elements parameter (deleting them) but that makes no difference.

Can you check on your side if the context.item is defined? Or do we need to do append our call in some way?

Kind Regards,

Ruben & Alfred

**Comment by Enngage** [comment]
Can you check if the content item is present in raw delivery response? The `context.item` is defined only when such item is in delivery response, thats why it is optional and not required.  I can't really test this on my own.

**Comment by rubenberendsen** [comment]
Hi Richard,

This is the response we get:

```
{
  "item": {
    "system": {
      "id": "6afd42e5-8f79-4f31-8120-fa5a10b44501",
      "name": "Disclaimer",
      "codename": "disclaimer",
      "language": "default",
      "type": "pagina",
      "sitemap_locations": [],
      "last_modified": "2019-12-10T09:08:08.7018403Z"
    },
    "elements": {
      "titel": {
        "type": "text",
        "name": "Titel",
        "value": "Disclaimer"
      },
      "sitemap": {
        "type": "taxonomy",
        "name": "Sitemap",
        "taxonomy_group": "sitemap",
        "value": []
      },
      "teaser_tekst": {
        "type": "text",
        "name": "Teaser tekst",
        "value": ""
      },
      "header_afbeelding": {
        "type": "asset",
        "name": "Header afbeelding",
        "value": []
      },
      "introductie_tekst": {
        "type": "text",
        "name": "Introductie tekst",
        "value": "Lees hieronder onze disclaimer voor .\n\n"
      },
      "artikel_tekst": {
        "type": "rich_text",
        "name": "Artikel tekst",
        "images": {},
        "links": {
          "e215dce4-ecca-4544-88ab-7dab9838dd61": {
            "codename": "supervisor_worden",
            "type": "pagina",
            "url_slug": "supervisor-worden"
          }
        },
        "modular_content": [
          "n29926339_2406_01bc_c6b0_90c7a7c0a9f2"
        ],
        "value": "<p>Het <a data-item-id=\"e215dce4-ecca-4544-88ab-7dab9838dd61\" href=\"\">doel </a>van deze2 website is het geven van informatie, niet van het geven van opvoedkundig advies. De informatie is met zorg samengesteld </p>\n<p><br></p>\n<object type=\"application/kenticocloud\" data-type=\"item\" data-rel=\"component\" data-codename=\"n29926339_2406_01bc_c6b0_90c7a7c0a9f2\"></object>\n<p><br></p>"
      },
      "downloads": {
        "type": "modular_content",
        "name": "Downloads",
        "value": []
      },
      "gerelateerde_pagina_s": {
        "type": "modular_content",
        "name": "Gerelateerde pagina's",
        "value": []
      },
      "seo_element__seo_titel": {
        "type": "text",
        "name": "SEO Titel",
        "value": ""
      },
      "seo_element__seo_meta_description": {
        "type": "text",
        "name": "SEO Meta description",
        "value": ""
      },
      "seo_element__seo_meta_keywords": {
        "type": "text",
        "name": "SEO Meta keywords",
        "value": ""
      },
      "url": {
        "type": "url_slug",
        "name": "URL",
        "value": "disclaimer"
      }
    }
  },
  "modular_content": {
    "n29926339_2406_01bc_c6b0_90c7a7c0a9f2": {
      "system": {
        "id": "29926339-2406-01bc-c6b0-90c7a7c0a9f2",
        "name": "29926339-2406-01bc-c6b0-90c7a7c0a9f2",
        "codename": "n29926339_2406_01bc_c6b0_90c7a7c0a9f2",
        "language": "default",
        "type": "downloads",
        "sitemap_locations": [],
        "last_modified": "2019-12-10T09:08:08.7018403Z"
      },
      "elements": {
        "titel": {
          "type": "text",
          "name": "Titel",
          "value": "Dit is een test"
        },
        "selecteer_het_bestand": {
          "type": "asset",
          "name": "Selecteer het bestand",
          "value": [
            {
              "name": "20192.jpg",
              "description": null,
              "type": "image/jpeg",
              "size": 15406,
              "url": "https://assets-eu-01.kc-usercontent.com:443/eb0d3718-d874-0101-77f7-326ae9b49004/c052e466-50e9-436b-864a-0937714b60c2/20192.jpg",
              "width": 200,
              "height": 267
            }
          ]
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/38040580/70725117-18b3e300-1cfc-11ea-9114-dd0e526719d2.png)

This is the GUID of the item we need to UrlResolve.

The item we include in the rich text as a component is included in the modalur_content (that's great). We expected the same for the content link in the richtext editor.

This is our richtext editor in KenticoKontent:
![image](https://user-images.githubusercontent.com/38040580/70725525-d4751280-1cfc-11ea-911c-80b3cad2f3a9.png)

**Comment by Enngage** [comment]
Hey Ruben,

I see what you mean. I tested it on my own too and Delivery API does not include item linked as link in the response. I asked around and currently there is no way to enforce this. I added a feature request internally, however currently the only solution seems to be using either **components** or **linked items** in the rich text instead. Then, you can use `richTextResolver` and transform it into a link.

**Comment by rubenberendsen** [comment]
Hi Richard,

It will be great if it will be fixed, You can indicate when this will be picked up or when it will work in this JS SDK?

**Comment by Enngage** [comment]
Hi Ruben,

I think this is rather a new feature rather then a bug. The initial idea was to rely on url slug only when using link in combination with linked item. Your scenario is a bit different and there is good workaround with components so I don't think there will be any change to this behavior any time soon. But it really depends on our product managers, there is only so much I can do :)

**Comment by Enngage** [comment]
Closing for now as this is related to product itself and there is not much sdk can do.
