### ISSUE TITLE
Add support to resolveHTML for an image

### ISSUE THREAD

**Issue by surfinzap** [Kentico/kontent-delivery-sdk-js#272]
### Motivation
This is how Image is resolved in Rich-text element today:
```
<figure>
	<img src="">
</figure>
```
For our project we need to render image in the following way:
```
<figure>
	<img src="">
	<figcaption>caption</figcaption>
</figure>
```

### Proposed solution
Ideally, I would able to extend resolver for an image su supply my desired HTML markup.

**Comment by Domitnator** [comment]
@surfinzap You have to implement the [richTextResolver ](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md#resolving-content-items-and-components-in-rich-text-elements)for that and make sure you insert the image as a component (so you might also need to create a new content model for that):

![image](https://user-images.githubusercontent.com/13468638/70515133-1f442e00-1b35-11ea-9461-34ab88cba965.png)

**Comment by surfinzap** [comment]
@Domitnator thanks! That's exactly how I worked around it. But from the perspective of content editor, it is an unnecessary step I have to teach them. That's why it would be better to be able to write own resolver for images.

**Comment by Enngage** [comment]
This feature is available in the next version of the SDK as can be demonstrated by following test (https://github.com/Kentico/kontent-delivery-sdk-js/blob/vnext/test/browser/isolated-tests/resolvers/browser-rich-text-resolver/browser-rich-resolver-html-priority.spec.ts#L29)
