### ISSUE TITLE
href not set even though urlSlugResolver is set

### ISSUE THREAD

**Issue by chaelli** [Kentico/kontent-delivery-sdk-js#273]
### Brief bug description

In the react tutorial (https://docs.kontent.ai/tutorials/develop-apps/get-started/building-your-first-react-app-part-2) a urlSlugResolver is used for - I assumed - writing correct urls into the links. But when I open http://localhost:3000/post/coffee-processing-techniques the link in the richtext ( delicious cup lying on your table) has no href.

### Repro steps

1. Clone https://github.com/Kentico/kontent-tutorial-react-js
2. npm i; npm start
3. go to http://localhost:3000/post/coffee-processing-techniques
4. See missing href

### Expected behavior

I would expect the href to be set correctly (even though the links are handled in JS).

### Test environment

 - Platform/OS: react / win10
 - Browser MS Edge (chromium)
 - Version 80.0.355.1

### Additional context

I found the issue while I tried to use next.js links and would have needed the href attribute (I know I can work around it.. but.. )

**Comment by CollierCZ** [comment]
HI @chaelli. The issue you described here was about the implementation of the React tutorial (which was initially written a few versions of the Delivery SDK ago). When implementing a link resolver, it's now best to define the url property of an object, as you can see in the [commit](https://github.com/Kentico/kontent-tutorial-react-js/commit/a7cd4d982083eb49a42b94b68c29a5e9a65850b7) that added the href back to the React sample. I also updated the examples in the tutorial.
Please let me know if I missed anything or if anything's unclear.

**Comment by chaelli** [comment]
thanks! That worked perfectly
