### ISSUE TITLE
Implement resolution to `itemsFeedAll` method

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-js#275]
### Motivation

Related to https://github.com/Kentico/gatsby-source-kontent/issues/97

From the 1st of February the `/items` endpoint is limited to 1000 (incl. linked items) as described in [Kontent API changes](https://docs.kontent.ai/reference/api-changelog#a-delivery-api-limitation).
After that date, queries resulting in more than 1K content items per language won't load more than that 1K items.

By using alternative endpoint `items-feed` respectively `itemsFeedAll` from JS SDK users would lose the ability to relive URLs as well as linked items + components (as described in the issue linked abouve).

### Proposed solution

Implement resolution the same way as using the `items` method.

### Additional context

Including the `content.item` value in `URLSlug resolver`:

```js
module.exports = class Page extends ContentItem {
  constructor() {
    super({
      urlSlugResolver: (link, context) => {
        const entry = context.item // THIS ONE
        const [parentElement] = entry ? entry.parent_element.value : []

        return {
          url: `${parentElement ? `/${parentElement.url_slug.value}` : ``}/${
            entry.url_slug.value
          }`,
        }
      },
    })
  }
}
```

**Comment by Enngage** [comment]
fixed by https://github.com/Kentico/kontent-delivery-sdk-js/commit/6e304856fda0a7d9c55e2910dac2578014cedc37
