### ISSUE TITLE
Document `itemsFeedAll` method

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-js#277]
### Motivation

Since the SDK supports [`/items-feed`](https://docs.kontent.ai/reference/delivery-api#operation/enumerate-content-items) endpoint, it would be great to have the mention in the [Full documentation](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md).

**Comment by Enngage** [comment]
This methods has been removed in next (https://github.com/Kentico/kontent-delivery-sdk-js/commit/7c68b8f910a1bf55c1ec6954c560d6e9f912c3c3) and the alternative is to simply use `toAllObservable` on the items feed (and all other listing) query
