### ISSUE TITLE
Angular 8 compatibility with AngularHttpService

### ISSUE THREAD

**Issue by mahpour** [Kentico/kontent-delivery-sdk-js#280]
### Brief bug description

Using AngularHttpService from `kentico-cloud-angular-http-service` is causing npm audit warnings in an upgraded angular project at v8.x:

```
npm WARN kentico-cloud-angular-http-service@3.0.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN kentico-cloud-angular-http-service@3.0.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```
### Repro steps

1. `npm install kentico-cloud-angular-http-service` 

### Expected behavior

There should be an updated angular implementation for `IHttpService`  that's using angular `HttpClient` not `axios` for SSR compatibility 

### Additional context
Angular universal needs async http calls to wait before it renders the page. Other libraries like axios have not been tuned yet to support angular universal rendering. So the support to native angular HttpClient library is still needed.

**Comment by Enngage** [comment]
Hi, 

The library you mentioned is located in this repository: https://github.com/Kentico/kontent-angular-http-service

I've updated the code and released a new `3.0.0` version with updated core HTTP service & Angular 8. Let me know how that works.
