### ISSUE TITLE
Update code examples - resolveHtml is no longer valid

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-js#282]
According to @mvhoute:
https://gitter.im/Kentico/Kontent?at=5e4d50a389f30b12651899fa

`resolveHtml` is no longer valid.

It can be found at:
https://docs.kontent.ai/tutorials/develop-apps/get-content/dealing-with-structure-in-rich-text?tech=javascript#a-resolving-tweets-within-rich-text
![image](https://user-images.githubusercontent.com/9810625/74915816-2608e000-53c5-11ea-8a3a-74c4b3d758e2.png)

Please verify if it's really the case and update all occurrences of rich text resolution according to the new best practice.

**Comment by Enngage** [comment]
Hey, 

The `resolveHtml` method is valid and is one of 2 options you can use to resolve HTML in rich text elements (see https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/lib/elements/elements.ts#L213)

The other option is to call `resolveData` which gives you additional, contextual information. 

From the gitter it seems the question relates to the gatsby plugin which creates its own `resolvedData` property for rich text elements. From looking at the code, it seems the property should be there - https://github.com/Kentico/gatsby-source-kontent/blob/master/src/decorators/richTextElementDecorator.js#L54 

I would suggest updating to latest version of Gatsby plugin.
