### ISSUE TITLE
How to resolve an item from its url?

### ISSUE THREAD

**Issue by zamponotiropita** [Kentico/kontent-delivery-sdk-js#284]
I want to access an item from its URL value (e.g `example.com/blog/a-landing-page-this-page-is-built-by-linking-other-content`) since that's the only information I have when accessing my article through the browsers URL. The only way I made it work so far was using the _Codename_ as the articles URL and then using that to fetch the item, but that's not SEO friendly. (`example.com/blog/landing_page_with_product_listing` vs `example.com/blog/a-landing-page-this-page-is-built-by-linking-other-content`) 
I think it's also overkill to fetch all my items and then filter out the one which matches with my URL.

Did I miss anything from the docs? Any way to make it work directly through the items URL value?

**Comment by ChristopherJennings** [comment]
Hi @zamponotiropita, 

There are a couple of approaches you can take here. 

The first is simple, but could be considered "dirty". For this approach you would "slugify" the codename. Essentially, all you'd do is replace the `_` with `-` when creating URLs and reverse that when making the query to Kontent. 

The second, probably better, option is to use the URL Slug element [as described in the documentation](https://docs.kontent.ai/tutorials/develop-apps/optimize-for-the-web/creating-seo-friendly-urls#a-url-slug-in-content-items). Then when you need to retrieve this item you use filtering options in the SDK/API to get the item. When [using the SDK to filter](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md#filtering), that'd look something like this:

```
deliveryClient.items()
  .type('your_type')
  .equalsFilter('elements.url_slug_element_codename', 'your-url-value')
  .toObservable()
  .subscribe(response => console.log(response));
```

**Comment by zamponotiropita** [comment]
Thanks for the great reply. I'll go with the first solution, since the second one fetches all items over the network and does the filtering locally. I don't know if there are many other customers experiencing the same use-case, but if so, fetching an item from it's URL directly would also save bandwidth from your side

**Comment by ChristopherJennings** [comment]
Either option is fine depending on your particular situation, but I do want to point out that the second option does the filtering using Kontent's delivery API filtering. The only data sent over the network is the items that match the filter, which in this case should just be the one item with that URL slug.

You can find more details about [how filtering works with the API in the docs](https://docs.kontent.ai/reference/delivery-api#tag/Filtering-content). 

Thanks for reaching out and good luck on your projects!

**Comment by zamponotiropita** [comment]
@ChristopherJennings thanks for your good explaination!
