### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by Corjen** [Kentico/kontent-delivery-sdk-js#287]
Hi all,

Currently the bundle size of kontent-delivery-sdk-js is quite high, due to the parse5 & rxjs dependencies. Are there any plans for a light-version of the sdk or saving some kb's from the bundle?

**Comment by Enngage** [comment]
Hi,

There already is a umd bundle without `parse5` dependency - https://github.com/Kentico/kontent-delivery-sdk-js#kontent-deliverybrowserumdmin

Is this what you need? :-)

**Comment by Corjen** [comment]
Thanks for the quick reply! Is there a way I can import that bundle in typescript? 

Using `import { DeliveryClient, TypeResolver } from '@kentico/kontent-delivery'` still puts the parse5 lib in the bundle

**Comment by Corjen** [comment]
To give some context, we're running a next.js app which exports both a server and a client bundle.

We would like to be able to let webpack switch between a node and a browser version of. the sdk, like this:
```
 if (!options.isServer) {
   config.resolve.alias['@sentry/node'] = '@sentry/browser'
   config.resolve.alias['@kentico/kontent-delivery'] ='@kentico/kontent-delivery/_es2015'
 }
```

It seems though that the es2015 bundle also includes parse5, is that correct? Is there a way to get the browser bundle using import?

**Comment by Enngage** [comment]
You can treat it like any other javascript UMD module and using it like 

```const sdk = require('@kentico/kontent-delivery/_bundles/kontent-delivery.umd.min');```

But you lose all typings. There are no special types for specific bundles. It's possible we could distribute some, but I'm not exactly sure how that would work. 

What I would recommend instead is to keep using imports as you are used to and configure your webpack to **remove** certain libraries from the final bundle. This is by far the easiest approach you can do. I'm actually using exactly this to generate the browser bundle in the first place. Take a look here: https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/webpack.browser.config.js#L22

**Comment by Corjen** [comment]
Cool! That saved over 75k gzipped size. Thanks for the support :) 

For anyone stumbling on this issue, i've fixed it by adding this to our webpack config in `next.config.js`: 

```
if (!options.isServer) {
  config.resolve.alias["@kentico/kontent-delivery"] =
    "@kentico/kontent-delivery/_es2015";
  config.externals = [
    "parse5",
    /^parse5\//,
    {
      rxjs: {
        commonjs: "rxjs",
        commonjs2: "rxjs",
        amd: "rxjs",
        root: "rxjs"
      },
      "rxjs/operators": {
        commonjs: "rxjs/operators",
        commonjs2: "rxjs/operators",
        amd: "rxjs/operators",
        root: ["rxjs", "operators"]
      }
    }
  ];
}
```
