### ISSUE TITLE
Add typeResolvers dynamically

### ISSUE THREAD

**Issue by ematipico** [Kentico/kontent-delivery-sdk-js#289]
### Motivation

On a big code base that is not a SPA, the whole client will pull all the models from the entire website and only a bunch of them are used in one single page.

It would be great if once created an instance of `DeliveryClient`, it was possible to add type resolvers dynamically.

During minification/bundling, ALL the models will be pulled inside the same bundle. This is not good because it will increase the bundle size for nothing

### Proposed solution

```js
const client = new DeliveryClient();

client.addTypeResolvers([
   new TypeResolver('foo'),
   new TypeResolver('bar'),
])

```

### Additional context

I read the whole documentation an there's nothing around this feature. Unless I missed somewhere, could you please point me?
I also checked old issues and couldn't find anything.

**Comment by Enngage** [comment]
Hi @ematipico,

How many models are you talking about? Usually, the models are just a couple of KBs and with Gzip its even less. Is there any reason you cannot create new instance of delivery client on each page? Just trying to wrap my head around the scenario :-)

**Comment by ematipico** [comment]
They are around 150/200 and counting, they will keep growing of course.

We have a Next.js application which, at the moment, it behaves like a website. This means that every subsequent navigation behaves like a SPA, where the content is fetched in the client side AFTER the page is rendered to the screen.

**Comment by Enngage** [comment]
Can you try using the following code?

```typescript
const client = new DeliveryClient(...);
client.config.typeResolvers = [
   new TypeResolver('foo'),
   new TypeResolver('bar'),
];
```

If you are using typescript you might need to change typing for client prop - 

```typescript
const client = new DeliveryClient(...) as any;
client.config.typeResolvers = [
   new TypeResolver('foo'),
   new TypeResolver('bar'),
];
```

I haven't tested this myself, but looking at code it should be sufficient to do. I can come up with a better way to tackle this by exposing public API, but in the meantime this could help. 

On a different note - there is a proposal to remove (separate) rxjs dependency in our core javascript library which will effectively reduce size of all javascript sdks by about 80KB.

**Comment by ematipico** [comment]
> On a different note - there is a proposal to remove (separate) rxjs dependency in our core javascript library which will effectively reduce size of all javascript sdks by about 80KB.

That would be a huge improvement, we don't actually use the reactive part of the library and even so we pull that part in the final bundle.

**Comment by Enngage** [comment]
Type resolvers are completely removed in new version of this library which will favor interfaces instead of classes for easier use & reduced size & complexity.
