### ISSUE TITLE
Extract ImageUrlBuilder to separate package

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-js#290]
### Motivation

Sometimes, you just need to use Image transformation on the client. It would be great to be able to use it without dependency on the delivery client.

### Proposed solution

Extract `ImageUrlBuilder` to separate npm package. And maybe make it a fixed version dependency of this package.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

Move documentation for [Image transformations](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md#image-transformations) to the newly created package.

**Comment by Enngage** [comment]
Thats a good idea, I'll take a look at this :-)

**Comment by Enngage** [comment]
I'll probably leave image url builder as a part of this delivery SDK as having a separate npm package for just a "simple & short" code is a little bit of an overkill. The new version of SDK is also a lot smaller (17KB when gzipped) so it shouldn't really be a problem for a majority of cases.
