### ISSUE TITLE
SDK uses incorrect parameter value for image optimization - auto parameter

### ISSUE THREAD

**Issue by tomasjurasek** [Kentico/kontent-delivery-sdk-js#296]
### Brief bug description

The SDK uses incorrect parameter value for the image optimization for the auto parameter.
The problem is that the SDK appends `auto=webp` instead of `auto=format` to the image URL - [image-url-builder:75](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/lib/images/image-url-builder.ts#L75).

### Repro steps
Example image - https://assets-eu-01.kc-usercontent.com/65954118-2d7a-016c-9a3c-c4dc9d4d941f/114be976-6ac8-4356-87de-32b67d930471/IMG_20180316_110120.jpg?auto=format

When you change the 'auto=webp' to 'auto=format'

### Expected behavior

Convers to WEBP (if the browser supports it).

Response header: image/webp

### Test environment

 - Windows, Chrome

**Comment by Enngage** [comment]
Fixed & released in `9.2.1`
