### ISSUE TITLE
Add support for new filtering operators

### ISSUE THREAD

**Issue by huluvu21** [Kentico/kontent-delivery-sdk-js#297]
### Motivation

The reason for new filtering operators is to give the users of our API better tools for getting just the content they need.

### Proposed solution

Add the new filtering operators mentioned in the [Kentico Kontent product changelog](https://docs.kontent.ai/changelog/product-changelog#a-new-filtering-operators-for-delivery-api).

### Additional context

You may look at the implementation for [.NET](https://github.com/Kentico/kontent-delivery-sdk-net) for a reference (i.e. [EmptyFilter](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/Urls/QueryParameters/Filters/EmptyFilter.cs)).

**Comment by Enngage** [comment]
Released in `10.0.0`
