### ISSUE TITLE
One Function for all the filters

### ISSUE THREAD

**Issue by prakharb147** [Kentico/kontent-delivery-sdk-js#298]
### Motivation

Why is this feature required? What problems does it solve?
To be able to use one method for filtering content rather than using functions like, _type, types, allFilter, anyFilter, containsFilter_.
### Proposed solution
One function with a param that understands and performs filtering using that param. E.g. `client.getEntries(params)`
An ideal solution for the above problems.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by Enngage** [comment]
@prakharb147 You may use `withParameters` extension method for this purpose :-) 

In it you pass array of parameters from `Parameters` interface.
