### ISSUE TITLE
global urlSlugResolver does not work

### ISSUE THREAD

**Issue by michaelwindell26** [Kentico/kontent-delivery-sdk-js#299]
### Brief bug description

`urlSlugResolver` only appears to work on a per query basis.

#### Resolves links
```js
.queryConfig({
  urlSlugResolver: (link, context) => ({
    url: link.urlSlug ? `/${link.urlSlug}` : '#'
  })
})
```

#### Does not resolve links
```js
globalQueryConfig: {
  urlSlugResolver: (link, context) => ({
    url: link.urlSlug ? `/${link.urlSlug}` : '#'
  })
}
```

### Expected behavior

`urlSlugResolver` should work when set through `globalQueryConfig`

**Comment by Enngage** [comment]
Hey @michaelwindell26,

Did you register `TypeResolvers` in your delivery client initialization?

**Comment by michaelwindell26** [comment]
@Enngage Yes i did, using the autogenerated models from [@kentico/kontent-model-generator](https://github.com/Kentico/kontent-model-generator-js) and these are working as expected.

**Comment by Enngage** [comment]
Are you sure that the type of the item you are trying to resolve is the one for which you registered global resolver? I'm simply asking because we have tests confirming that global resolvers work (e.g. https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/test-browser/isolated-tests/resolvers/url-slug-resolver.spec.ts#L57)

**Comment by michaelwindell26** [comment]
Ahh, maybe a miscommunication. 

I am using `resolveHtml` for `RichTextElement` types rather than `resolveUrl` directly. Would that make a difference?

**Comment by Enngage** [comment]
Looking at the code, I don't think so. Global URL resolvers are used for `RichTextElement`, Can you provide a repro on stackblitz? That is probably the best way to see whats going on.
