### ISSUE TITLE
Add support for content collections

### ISSUE THREAD

**Issue by RadoslavK** [Kentico/kontent-delivery-sdk-js#300]
### Motivation

Support for content collections is being added to Deliver.

### Additional context

- System model contains collection's codename
- It is possible to filter items by collections

**Comment by petrsvihlik** [comment]
could you please give this one higher priority @Enngage ? thx!

**Comment by Enngage** [comment]
@petrsvihlik oh, this was released 12 days ago :) I forgot about the issue, so closing now.

**Comment by petrsvihlik** [comment]
could you also please add a corresponding record to [releases](https://github.com/Kentico/kontent-delivery-sdk-js/releases)?
