### ISSUE TITLE
kcl-4508 introduce new system property (workflow_step) in item object

### ISSUE THREAD

**Issue by Sevitas** [Kentico/kontent-delivery-sdk-js#309]
### Motivation

Introduces new system property 'workflow_step' representing codename of the workflow step, an item is assigned to. Items can be filtered out based on this property

### Proposed solution

Introduce new property to system object of items. Components should not contain this property.

### Additional context

https://kentico.atlassian.net/browse/KCL-6343

Changing of workflow step's codename updates all codenames in items, which are assigned to this workflow step.

Request to preview API for content items:
new response: `{
    "items": [
        {
            "system": {
                "id": "a7d8617e-1081-405e-80ea-8cfa07fc1a29",
                "name": "review",
                "codename": "review",
                "language": "default",
                "type": "sdasd",
                "collection": "default",
                "sitemap_locations": [],
                "last_modified": "2021-02-01T19:00:39.7453619Z",
                "workflow_step": "review_hatatitla"
            },
            "elements": {
                "untitled_text": {
                    "type": "text",
                    "name": "Untitled text",
                    "value": ""
                },
                "untitled_rich_text": {
                    "type": "rich_text",
                    "name": "Untitled rich text",
                    "images": {},
                    "links": {},
                    "modular_content": [
                        "vvvvv"
                    ],
                    "value": "<object type=\"application/kenticocloud\" data-type=\"item\" data-rel=\"link\" data-codename=\"vvvvv\"></object>"
                }
            }
        }
    ],
    "modular_content": {
        "vvvvv": {
            "system": {
                "id": "d4d0d85f-5545-45ba-b587-23f276da5e56",
                "name": "vvvvv",
                "codename": "vvvvv",
                "language": "default",
                "type": "sdasd",
                "collection": "default",
                "sitemap_locations": [],
                "last_modified": "2021-02-01T18:57:36.9493395Z",
                "workflow_step": "draft"
            },
            "elements": {
                "untitled_text": {
                    "type": "text",
                    "name": "Untitled text",
                    "value": ""
                },
                "untitled_rich_text": {
                    "type": "rich_text",
                    "name": "Untitled rich text",
                    "images": {},
                    "links": {},
                    "modular_content": [],
                    "value": "<p><br></p>"
                }
            }
        }
    },
    "pagination": {
        "skip": 0,
        "limit": 0,
        "count": 1,
        "next_page": ""
    }
}`

old response: `{
    "items": [
        {
            "system": {
                "id": "a7d8617e-1081-405e-80ea-8cfa07fc1a29",
                "name": "review",
                "codename": "review",
                "language": "default",
                "type": "sdasd",
                "collection": "default",
                "sitemap_locations": [],
                "last_modified": "2021-02-01T19:00:39.7453619Z",
                "workflow_step": "review_hatatitla"
            },
            "elements": {
                "untitled_text": {
                    "type": "text",
                    "name": "Untitled text",
                    "value": ""
                },
                "untitled_rich_text": {
                    "type": "rich_text",
                    "name": "Untitled rich text",
                    "images": {},
                    "links": {},
                    "modular_content": [
                        "vvvvv"
                    ],
                    "value": "<object type=\"application/kenticocloud\" data-type=\"item\" data-rel=\"link\" data-codename=\"vvvvv\"></object>"
                }
            }
        }
    ],
    "modular_content": {
        "vvvvv": {
            "system": {
                "id": "d4d0d85f-5545-45ba-b587-23f276da5e56",
                "name": "vvvvv",
                "codename": "vvvvv",
                "language": "default",
                "type": "sdasd",
                "collection": "default",
                "sitemap_locations": [],
                "last_modified": "2021-02-01T18:57:36.9493395Z"
            },
            "elements": {
                "untitled_text": {
                    "type": "text",
                    "name": "Untitled text",
                    "value": ""
                },
                "untitled_rich_text": {
                    "type": "rich_text",
                    "name": "Untitled rich text",
                    "images": {},
                    "links": {},
                    "modular_content": [],
                    "value": "<p><br></p>"
                }
            }
        }
    },
    "pagination": {
        "skip": 0,
        "limit": 0,
        "count": 1,
        "next_page": ""
    }
}`

**Comment by Enngage** [comment]
Implemented in vnext

**Comment by yarandoo** [comment]
@Enngage, thanks! Keen on this feature, do you have an ETA for the next release, or where I could look for release updates?

**Comment by Enngage** [comment]
Hey @yarandoo, I'm planning on releasing first `preview` version sometime next month. The full `latest` version will be available later on based on additional feedback. Do however note that the next version is fundamentally different and there will be a need for you to adjust the code. One of the things we are doing is for example removing `rxjs`, improving types and changing most of models & queries for better developer experience. 

It should really be a lot easier to use, but it will not be a simple dependency update.
