### ISSUE TITLE
Update Kentico-core-js to 9.1.0

### ISSUE THREAD

**Issue by rickvandermey** [Kentico/kontent-delivery-sdk-js#321]
### Brief bug description

the last release date of 8.1.0 is january 2021, and would like to stay up to date with all devDependencies, because axios has a critical bug that should be fixed.

**Comment by Enngage** [comment]
@rickvandermey hey, yeah, this SDK is in development and will have a major release in near future. I'm hoping to get it up in 3 months. There are gonna be a lot of breaking changes, so there will be preview versions released sooner.

**Comment by Enngage** [comment]
Kontent-core-js is updated to latest version in `vnext` branch (https://github.com/Kentico/kontent-delivery-sdk-js/tree/vnext)

Preview versions of this refactored sdk will be published on npm in upcoming weeks.
