### ISSUE TITLE
Add support for asset renditions

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-delivery-sdk-js#327]
### Motivation

New Kontent feature - Asset renditions, will be released soon (beginning of December with) and it will be available through DeliveryAPI. We should have them covered in SDKs as well.

### Proposed solution

When the asset element is retrieved from Deliver, the referenced assets can now contain user-defined renditions and it is easy for the developer to apply the rendition query string to the URL of the original asset so that the customized image can be rendered in the UI.

### Additional context

This is the updated Deliver contract for referenced assets of asset element: 
* New `renditions` property is present and it is a dictionary with a single key (for now) equal to the "default" preset codename. Presets are not a real entity for now but are part of the long-term vision of asset renditions.
* If no renditions were defined for the asset, an empty object is present in the `renditions` property.
* Note, that this only applies to assets in the asset element. There is no support for renditions in inline RTE images, yet.
```
{
    "name": "name-of-the-uploaded-file.jpg",
    "type": "image/jpeg",
    "size": 90895,
    "description": "Description of what the asset represents.",
    "url": "https://assets-us-01.kc-usercontent.com/975bf280-fd91-488c-994c-2f04416e5ee3/3e76909f-599f-4742-b472-77fd4b510e92/sources.jpg",
    "width": 1000,
    "height": 666,
    "renditions": {
      "default": {
        {
          "rendition_id": "d44a2887-74cc-4ab0-8376-ae96f3f534e5",
          "preset_id": "a6d98cd5-8b2c-4e50-99c9-15192bce2490",
          "width": 200,
          "height": 150,
          "query", "w=200&h=150&fit=clip&rect=7,23,300,200"
      }
    }
}
```

**Comment by Suzii** [comment]
Will be handled by Westplex team internally.

**Comment by Enngage** [comment]
Fixed by https://github.com/Kentico/kontent-delivery-sdk-js/commit/8cbe9916b95c8a95396211a53ef8de4e0a4850b1

**Comment by Suzii** [comment]
Hi, just one thing about the fix: It is not really `renditionCodename` but rather `renditionPresetCodename`.

**Comment by Enngage** [comment]
I've updated the indexer name, thank you @Suzii  :) However, since this is just an indexer type, we can call it whatever we like ;) 

Also, I'll add some more tests & absolute asset URLs for the renditions in the upcoming days.

**Comment by Suzii** [comment]
Hi, I am really sorry, but as we are still developing the feature, there has been a slight change of plans. The new property `renditions` won't be present at all times, but rather only for "image-like" objects:
* the property will only be present for image-like objects (those which have both `width` & `height` properties set by the system)
* when no renditions are defined for the linked asset, the empty object/dictionary is returned in the rendition property
* if the asset is of non-image type (e.g. .pdf) the property won't be present (same as `width` & `height` in that case)

I'm not sure whether anything needs to be adjusted. I updated all the other SDKs issue descriptions. Sorry for the inconvenience.

ping @Enngage
