### ISSUE TITLE
Failed to resolve entry for package

### ISSUE THREAD

**Issue by Domitnator** [Kentico/kontent-delivery-sdk-js#329]
Hi Richard,

Nuxt 3 is still in beta (https://v3.nuxtjs.org/) and i wanted to test if the kentico-kontent-nuxt-module is already compatible with Nuxt 3. So I first created a Nuxt 3 project to test the kontent-delivery-sdk-js itself: 

1. Installed a new Nuxt 3 project (npx nuxi init nuxt3-app)
2. Installed kontent-delivery-sdk-js via NPM
3. Added some basic code to do a delivery call:

![image](https://user-images.githubusercontent.com/13468638/142992226-26578e90-d7c8-44e6-82b2-b7263694dbc1.png)

I then get an error:

![image](https://user-images.githubusercontent.com/13468638/142992694-1efb5241-171f-48ab-8c83-637105a57ba8.png)

My guess is that this has to do with the way the main exports are transpiled in the kontent-deliverty-sdk-js:

![image](https://user-images.githubusercontent.com/13468638/142997243-5b830eb0-54e3-4a71-849b-06cdedd420c3.png)

Maybe this is something specific to Nuxt 3 (beta) (which requires Node >14 and NPM > 6 and Nuxt 3 has full ESM support)? Or is this a broader issue?

Locally I managed to fix this issue (in a really quick and dirty fashion):
I forked the kontent-delivery-sdk-js, stripped away all build commands and replaced it with a Siroc (https://github.com/unjs/siroc#readme) based build:

![image](https://user-images.githubusercontent.com/13468638/143001551-c249185b-9687-4876-9373-cb3393cbee0c.png)

Then the error is gone BUT raises again for the "@kentico/kentico-core" package:

![image](https://user-images.githubusercontent.com/13468638/143001169-325f930e-63ab-4bb4-ae17-2c8c429d8ef3.png)

Let me know if you need more information. I could create a new repo to reproduce all this if you want?

FYI: I'm running Node version 16.13.0

**Comment by Domitnator** [comment]
@ondrabus Thanks for pointing out those repo's! I'll take a look at them!

**Comment by ondrabus** [comment]
@Domitnator np, please feel free to contribute, I appreciate your help! :)

**Comment by Enngage** [comment]
Thanks @ondrabus for the response! Closing this one as this is easily solved with framework configuration.
