### ISSUE TITLE
Depth Parameter not respected by SDK

### ISSUE THREAD

**Issue by benmorana** [Kentico/kontent-delivery-sdk-js#330]
### Brief bug description

When setting the `depthParameter` to `1`, we expected modular item values to not be resolved as part of the normal SDK behaviour (i.e value should either be an empty array or only contain the codename of the item, like in the REST API). However, we have found that if for example you set depth param `1`, but have a modular content item at level 2 (Content Item 1 -> Content Item 2 -> **Content Item 1**) that has already been included as part of the response at some other level (**Content Item 1** -> Content Item 2 -> Content Item 1), the SDK will automatically resolve the value of the modular content item at level 2. In cases where we are trying to avoid a circular dependency, this behaviour can be problematic.

### Repro steps

1. Create two content items with a Linked Item field.
2. Add the second content item as a linked item to the first content item **AND** the first content item as a linked item to the second.
3. Try to call the `item('codename_item_1')` method with a `depthParameter` of 1. 
4. Notice that the linked item field in the in the second content item resolves the value object of the first content item, essentially creating a circular dependency, even though we set the depth param to 1:
```
// This is the linked item element in the 2nd content item
          linked: LinkedItemsElement {
            rawData: {
              type: 'modular_content',
              name: 'Linked',
              value: [ 'content_1' ]
            },
            name: 'Linked',
            type: 'modular_content',
            itemCodenames: [ 'content_1' ],
            value: [ [Circular *1] ]
          },
```

### Expected behavior

SDK should not try to resolve content items at level `X` if `depthParameter` is set to `X-1`.

### Test environment

 - Platform/OS: Node V16.9.1
 - Version 10.4.1

### Additional context

Our current workaround (not ideal) involves cloning and manually cleaning-up the data before using it. Something similar to the below: 

```
export const limitModularContentDepth = ({ data, limit }: { data: IContentItem; limit: number }): IContentItem => {
  const iterate = (item: IContentItem, level: number) => {
    const object = item;
    const keys = Object.keys(object);
    keys.forEach((key) => {
      if ((object[key] as Elements.LinkedItemsElement).type === ElementType.ModularContent) {
        if (level < limit) {
          (object[key] as Elements.LinkedItemsElement).value.forEach((linkedItem) => {
            iterate(linkedItem, level + 1);
          });
        } else {
          (object[key] as Elements.LinkedItemsElement).value = [];
        }
      }
    });
    return object;
  };
  return iterate(clone(data), 0);
};

// JSON stringify will throw an error if there's a circular dependency so we use limitModularContentDepth to ensure nothing goes beyond depth of 1.
JSON.stringify(limitModularContentDepth({ data: itemData, limit: 1 })) 
```

**Comment by Enngage** [comment]
Hi @benmorana, this is really intended behavior and this will not be changed in `10.x.y` SDK. The `11.0.0` allows you to disable SDK mapping (see https://github.com/Kentico/kontent-delivery-sdk-js#handling-circular-references). 

Alternatively, you may use `flatted` package to handle circular JSON (https://www.npmjs.com/package/flatted)
