### ISSUE TITLE
Resolved content items are still within <object> tag

### ISSUE THREAD

**Issue by ondrabus** [Kentico/kontent-delivery-sdk-js#332]
### Brief bug description
After resolving rich text elements, the <object> tag describing the external resource persists.

### Repro steps

1. Resolve any rich text <object> element
2. The resolved content is still within the <object> tag that now also contains the `data-sdk-resolved` attribute

### Expected behavior

Once an external resource gets resolved, the <object> tag should be replaced with the resolved content.
According to https://www.w3schools.com/tags/tag_object.asp the <object> tag is supposed to mark only external content, not resolved data.

### Additional context

Currently, the problem can be mitigated using the following regex:
.replace(/<object.*?data-sdk-resolved=\"1\".*?>(.*?)<\/object>/ms, '$1')
However, it's not a good practice to keep code fixes of SDK issues in the project code not to mention the external dependencies (the use of "<object>" tag and `data-sdk-resolved` attribute).

**Comment by ondrabus** [comment]
@Enngage any updates on this?

**Comment by Enngage** [comment]
@ondrabus I'm still not sure whether to use this or not. It's also a major change (unless we make this optional). The regex seems quite simple, but what if you want to use "object" within the resolver? I'm just not sure ;) @Simply007 has any opinion on this?

**Comment by ondrabus** [comment]
@Enngage I'm not saying it's the best solution :-) it's just a temp workaround that doesn't look good. Feel free to propose a better solution. I just want to get the problem that clearly exists solved :-)

**Comment by Simply007** [comment]
> @ondrabus I'm still not sure whether to use this or not. It's also a major change (unless we make this optional). The regex seems quite simple, but what if you want to use "object" within the resolver? I'm just not sure ;) @Simply007 has any opinion on this?

I would expect that `<object>` tag would be replaced by the resolution. On the other hand there are already people that used the resolver and they might expect to have the `<object>` tag being in the resolved HTML (i.e. they have some CSS selectors depending on it).

So I would choose between making it configurable, or changing the behavior (which is by the book breaking change).

**Comment by ondrabus** [comment]
@Enngage any updates on this?

**Comment by Enngage** [comment]
Will be released in next version. Currently, all <object> tags are removed by default. You can however set  `preserveResolvedObjectTags` of  `resolveRichText` method to preserve tags if needed.
