### ISSUE TITLE
Generic orderParameter function does no handle sort order (2nd parameter) not being set

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-js#335]
### Brief bug description

`orderParameter` results in an invalid URL in javascript.

### Repro steps

call `
```js
let URL = Client.items()
    .type('cafe')
    .orderParameter('system.name')
    .getUrl();
```

and you will get `.../items?system.type=cafe&order=system.name[undefined]`

### Expected behavior

Raise an exception when sort order is not specified.

### Context

I am aware of `orderByAscending` method. I was upgrading a project from DAPI SDK v10 and this behavior change was a bit tricky to uncover why I am getting 400 HTTP response status, that is why I am submitting it.

**Comment by Enngage** [comment]
The `orderParameter` cannot be called with a single parameter and we ship types describing the required parameters, so the solution would be to just use some IDE with intellisense to suggest both parameters. I wouldn't like to raise exception in all methods with parameters just in case some parameter is missing. 

You may call this method such as:

```typescript
client(responseJson).items().orderParameter('system.name', 'asc');

client(responseJson).items().orderParameter('system.name', 'desc');
```
