### ISSUE TITLE
Incorrect main/module/exports specified in package.json

### ISSUE THREAD

**Issue by CMeeg** [Kentico/kontent-delivery-sdk-js#340]
### Brief bug description

I am using a few Kontent packages in a project that is using Vite as the build tool. When I run `vite build` I receive errors like `Failed to resolve entry for package "@kentico/kontent-delivery". The package may have incorrect main/module/exports specified in its package.json.`.

If I look at the entries in [package.json](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/package.json#L37-L38) and compare to the package in `node_modules` it does seem to be an issue of incorrect paths being specified as, for example, `package.json` defines the `module` path as `./dist/esm5/index.js`, but there is no such path under `dist`.

This incorrect paths issue also seems to be the case in:

* [@kentico/kontent-delivery-node-parser](https://github.com/Kentico/kontent-delivery-node-parser/blob/master/package.json#L21-L22)
* [@kentico/kontent-core](https://github.com/Kentico/kontent-core-js/blob/master/package.json#L20-L21)
* [@kentico/kontent-model-generator](https://github.com/Kentico/kontent-model-generator-js/blob/master/package.json#L27-L28)

Not sure if there are others - these are the ones I happen to be using. If this is an issue that requires fixing, should I raise the same issue in each of those repositories?

### Repro steps

1. Go to [this repro on StackBlitz](https://stackblitz.com/edit/vitejs-vite-q3mxgq?file=main.js)
2. Run `npm run build` in the terminal
3. See error

### Expected behavior

There should be no "incorrect main/module/exports" error in the build and the build should succeed.

I have changed the paths in the `package.json` of my local `node_modules`, for example, set `"module": "./dist/esnext/index.js"` (as that path does exist) and can confirm this fixes the build error.

### Test environment

 - Platform/OS: Windows, TypeScript 4.5.5, Vite 2.8.4, Node 14.18.1
 - Kontent Delivery SDK JS: 11.3.0
 - Kontent Core: 9.4.0
 - Kontent Model generator: 4.1.0
 - Kontent Node parser: 1.1.0

### Screenshots

![image](https://user-images.githubusercontent.com/940607/154844178-c77e7c38-8bb8-452d-90ea-50ccb501f5be.png)

**Comment by terence1988** [comment]
Hi CMeeg,
In the meantime, please check Vite's documents but I believe you only need to configure vite's bundler options as below
```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    mainFields: ["main","es6","module","jsnext"],
  },
  plugins: [vue()],
});
```
