### ISSUE TITLE
url-parse security vulnerability

### ISSUE THREAD

**Issue by cdhawke** [Kentico/kontent-delivery-sdk-js#342]
### Motivation

url-parse security vulnerability

### Proposed solution

upgrade the url-parse version to `> 1.5.7`

### Additional context

![image](https://user-images.githubusercontent.com/69921547/155988805-008493de-99fb-4fe7-8f07-c7c22a580671.png)

**Comment by Enngage** [comment]
Thanks @cdhawke, I've updated deps and will release new update soon.
