### ISSUE TITLE
RichText*Resolver requires to be run in a browser to work

### ISSUE THREAD

**Issue by PetrSvirak** [Kentico/kontent-delivery-sdk-js#343]
### Brief bug description

The `RichtText[Html|Json|Object]Resolver` does not work without a browser (e.g. on server-side in the Node.js). 
It worked on version [10.4.1](https://www.npmjs.com/package/@kentico/kontent-delivery/v/10.4.1), hence the bug (not a feature request).

### Repro steps

1. Spin a new next.js project (e.g. using [create-next-app](https://github.com/vercel/next.js/tree/canary/packages/create-next-app))
2. Add latest kontent-delivery-sdk-js (we use version [11.2.1](https://www.npmjs.com/package/@kentico/kontent-delivery/v/11.2.1) that is packed with no vulnerabilities) *
3. Add a page that will [render some content statically](https://nextjs.org/docs/basic-features/pages#static-generation-with-data) into the project
4. Add some Kontent to the page, using any of the parsers. **
   For example:
```javascript
export const getStaticProps = () => { 
    const data = await deliveryClient
      .item<…>(codename)
      .toPromise();
   const html = createRichTextHtmlResolver().resolveRichText(…).html
  
   return { props: { html} }
};

const Page: NextPage<InferCreatorStaticPropsType<typeof getStaticProps>> = ({ html }) => (
   <pre><code>{html}</code</pre>
);

export default Page;
```

5. See error in IDE/console window when trying to access the page
```text
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

### Expected behavior

At least one of the Parsers is not dependent on the browser and can be used in the node.js environment (such as Next.js's server-side) or there is an easy (or just documented?) way to plug-in a custom HTML parser, such as [himalaya](https://www.npmjs.com/package/himalaya).
### Test environment

 - Platform/OS: any
 - Browser: any
 - Version: any

### Additional context

\*: [the code](https://github.com/Kentico/kontent-delivery-sdk-js/blob/dc934984a1659768c6230d949d28c55197932d77/lib/parser/implementation/browser-parser.class.ts#L228) that causes the error is still present on the latest master branch – it is the `document` [variable is not defined](https://stackoverflow.com/questions/60629258/next-js-document-is-not-defined).

\**: Regards implementation/resolver code placement
1. we believe that the code belongs to the `getStaticProps` where it would be "stripped" off the rich Kontent model properties that are not needed
1. the code can be also be inserted into the `NextPage` page component, above the React components that Next should render (while it does not semantically belong there, it is easier to debug since errors are rendered to the page even if Next is configured to redirect on error)
1. one can see [one of possible workarounds](https://stackoverflow.com/a/60629302/1138663) implemented in our [pet project here](https://github.com/PetrSvirak/autoskolavav/blob/1a7f035c63dd1639966f58fe1a2201decb1225f3/components/article/index.tsx#L35) (we are currently using the `useEffect` hook)

**Comment by Enngage** [comment]
Hey @PetrSvirak,

The `node.js` parser has been separated into its own NPM package. You can install & use it based on this docs -> https://github.com/Kentico/kontent-delivery-sdk-js#resolving-rich-text-in-nodejs

The behavior should be practically identical to previous version of SDK.
