### ISSUE TITLE
Incorrect code example in README

### ISSUE THREAD

**Issue by MilanLund** [Kentico/kontent-delivery-sdk-js#350]
https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/readme.md#resolving-rich-text-in-nodejs

There is a code example stating:
```typescript
const html = await createAsyncRichTextHtmlResolver(asyncNodeParser).resolveRichText(data);
```
I think that is incorrect and should be:
```typescript
const html = await createAsyncRichTextHtmlResolver(asyncNodeParser).resolveRichTextAsync(data);
```
Also, the JSON one above looks a bit suspicious. However, have not had a chance to actually test it.

**Comment by Enngage** [comment]
You're right, thanks!
