### ISSUE TITLE
Cover model-generator package by tests

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-js#74]
### Motivation

It would be great to have [model-generator package](https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator) covered by tests to fulfill our best practices.

### Proposed solution

It would be great to:
* Set up testin framewrork infrastucture ideally the same as for delivery package:
    * [karma ](https://karma-runner.github.io/2.0/index.html)+ [jasmine ](https://jasmine.github.io/) for browser and [mocha ](https://mochajs.org/) for node.js
* Cover generating ES2015 + JavaScript 
* Cover generating ES2015 + Typescript
* Cover generating CommonJs + JavaScript

This issue could be split into more pull requests. You can use the proposed solution bullet points to split it. But still - configuring test infrastructure blocks other tasks.

### Additional context

Documentation for model generators: 
* https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator

**Comment by Enngage** [comment]
I'm closing this issue as it's quite old and any tests would have to be in the model generator repo.
