### ISSUE TITLE
Add support to generate TypeResolvers

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/kontent-delivery-sdk-js#76]
### Motivation
For the [Delivery Client](https://github.com/Enngage/kentico-cloud-js/tree/master/packages/delivery#kentico-cloud-delivery-sdk) creation, it is possible to provide [TypeResolver](https://github.com/Enngage/kentico-cloud-js/blob/master/packages/delivery/lib/models/item/type-resolver.class.ts), that is mapping content types fo the models (classes).

These models could be generated by the [model-generator](https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator) tool, that automatically generates models for the project (documentation).

**Current status**
There is no way, how to easily generate the skeleton for TypeResolvers to avoid the current busy-work. 

It would be great to have implemented in that generator a possibility to generate the type resolver too.

### Proposed solution

Creating a single file with that exports an array of all the necessary TypeResolvers would avoid the current busy-work. 

Some example 
* Mind the moduleResolution parameter for generation can influentce how the modules are imported and exported and also codeType parameter (https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator#configuration)

```
import { TypeResolver } from 'kentico-cloud-delivery';
import { Actor } from './actor.class';
import { Movie } from './movie.class';

const TypeResolvers = [
  new TypeResolver('actor', () => new Actor()),
  new TypeResolver('movie', () => new Movie())
];

module.exports = {
  TypeResolvers
}
```

**Comment by Simply007** [comment]
I have tried to make it more clear - @ChristopherJennings  - could you take a look if I got it right? :-)

**Comment by Pr0methean** [comment]
The links to https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator and https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator#configuration are both 404s.

**Comment by Enngage** [comment]
Hi @Pr0methean, where did you find these links? Yeah, the link you sent is the correct one.

**Comment by Pr0methean** [comment]
@Enngage They're in this issue's description.

**Comment by Enngage** [comment]
Next version of the SDK removed type resolvers as it favors interfaces instead of classes for reduced size & complexity. This change makes this issue obsolete.
