### ISSUE TITLE
[SPIKE] Describe pros and cons using type-graphql

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-js#89]
### Expected result

It is possible to describe fields by the decorators provided by delivery API:
* https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/lib/fields/field-types.ts
* https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/lib/fields/field-models.ts

Then implement the functionality to generate the schema by providing the schema definition from the delivery client.
* https://19majkel94.github.io/type-graphql/docs/emit-schema.html

Questions to answer:
* How to implement this functionality to the delivery SDK?
* Is it possible/beneficial to make a separate package for that?
* Is it OK to implement the only type generation and let users so implement queries + resolvers for these queries their own? ..suggest an approach

### Additional context

Mind the Kentico repository: https://github.com/Kentico/kentico-cloud-graphql-schema-generator/tree/master

### Resources

* https://github.com/19majkel94/type-graphql
* https://medium.com/@19majkel94/graphql-typescript-typegraphql-ba0225cb4bed
* https://19majkel94.github.io/type-graphql/

**Comment by Enngage** [comment]
I'm guessing this should be covered somewhere else in our docs, so I'm closing this issue for this SDK.
